name: gh-pages

on:
  push:
    branches:
      - master

permissions: 
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore
        
    - name: Publish
      run: dotnet publish StockBrain.WebApp/StockBrain.WebApp.csproj -c Release -o build/wwwroot --nologo --property:PublishTrimmed=false -p:BlazorEnableCompression=true -p:PublishSingleFile=false
      
    - name: Commit
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/wwwroot
        
        
        
