name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Substitua pelo nome do seu branch principal se for diferente

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Publish Blazor WebAssembly
      run: dotnet publish StockBrain.WebApp/StockBrain.WebApp.csproj -c Release -o release --nologo --property:PublishTrimmed=true -p:BlazorEnableCompression=true


    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: release/wwwroot

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2

    - name: List files in output directory
      run: ls -la release/wwwroot
