name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a branch principal do seu projeto, se necessário

  workflow_dispatch:  # Permite executar manualmente via GitHub Actions

permissions:
  contents: write  # Permissão para escrever na branch gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build e Publicação do Blazor WebAssembly
        run: dotnet publish -c Release -o release --nologo --p:StaticWebAssetBasePath=/StockBrain

      - name: Criar arquivo `.nojekyll` (Evita problemas com arquivos `_framework`)
        run: touch release/wwwroot/.nojekyll

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot  # Define a pasta de saída do Blazor
          clean: true  # Limpa a branch `gh-pages` antes do novo deploy
